backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "image"
    label: "Image"
    folder: "src/pages/image"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "image-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Doctor", name: "doctor", widget: "select", options: ["Dr. Smith", "Dr. Nelson", "Dr. Fountain"]}
      - {label: "Date", name: "date", widget: "date", format: "MMM Do YY"}
      - {label: "Image", name: image, widget: image, required: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}